### ISSUE TITLE
Self host image assets

### ISSUE THREAD

**Issue by codethebeard** [JoshuaDoshua/2016debatesonline#1]
Self host image assets to avoid cross-domain resource issues and complaints.

**Comment by JoshuaDoshua** [comment]
Great idea!
I'm sure there are plenty of public domain pics available

**Comment by codethebeard** [comment]
I went ahead and pulled a fork of this. Started looking around and didn't find a definitive place to pickup public domain images of the candidates. Any idea where I can look to grab public domain images of the candidates? I'll continue looking around in my free-time. If I can get them, I'll standardize them, upload, and create a pull request.

**Comment by JoshuaDoshua** [comment]
Wiki media commons would be my only guess...but even if they are all there, I'm sure those are inconsistent.

**Comment by codethebeard** [comment]
I'll take a look
